name: Auto-generate YouTube Chasers Placefile

on:
  workflow_dispatch:
  schedule:
    - cron: '*/15 * * * *'  # every 15 minutes

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      YOUTUBE_API_KEY: ${{ secrets.YOUTUBE_API_KEY }}
      GH_PAT: ${{ secrets.GH_PAT }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Run script to generate placefile
        run: python generate_placefile.py

      - name: Configure Git
        run: |
          git config user.name "marcosbombi"
          git config user.email "marcosbombi@users.noreply.github.com"
          git remote set-url origin https://x-access-token:${{ secrets.GH_PAT }}@github.com/marcosbombi/storm-chaser-placefile-for-supercellwx.git

      - name: Commit and Push changes
        run: |
          git add youtube_chasers.txt
          git diff --quiet && echo "No changes to commit" || (git commit -m "Auto-update placefile" && git push origin main)
