name: Update YouTube Placefile

on:
  schedule:
    - cron: "*/10 * * * *"  # runs every 10 minutes
  workflow_dispatch:       # allows manual run

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      YOUTUBE_API_KEY: ${{ secrets.YOUTUBE_API_KEY }}
      GH_PAT: ${{ secrets.GH_PAT }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install requests

      - name: Run script with debug
        run: |
          echo "Running Python script..."
          python generate_placefile.py

      - name: Commit and push updated placefile
        run: |
          git config user.name "marcosbombi"
          git config user.email "marcosbombi@users.noreply.github.com"
          git remote set-url origin https://x-access-token:${GH_PAT}@github.com/${{ github.repository }}
          git add youtube_chasers.txt
          git diff --quiet || (git commit -m "Auto-update placefile" && git push)