name: Update YouTube Storm Chaser Placefile

on:
  schedule:
    - cron: '*/15 * * * *'    # every 15 minutes
  workflow_dispatch:          # manual trigger allowed

jobs:
  update-placefile:
    runs-on: ubuntu-latest
    env:
      GH_PAT: ${{ secrets.GH_PAT }}
      YOUTUBE_API_KEY: ${{ secrets.YOUTUBE_API_KEY }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python 3.x
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install requests

      - name: Run placefile generator script
        run: python generate_placefile.py

      - name: List files in root
        run: ls -la

      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add youtube_chasers.txt
          if ! git diff --cached --quiet; then
            git commit -m "Auto-update placefile"
            git remote set-url origin https://x-access-token:${GH_PAT}@github.com/${{ github.repository }}.git
            BRANCH=${GITHUB_REF#refs/heads/}
            git push origin "$BRANCH"
          else
            echo "No changes to commit"
          fi
