name: Update YouTube Storm Chaser Placefile

on:
  schedule:
    - cron: '*/15 * * * *'    # every 15 minutes (adjust as needed)
  workflow_dispatch:          # allow manual trigger

jobs:
  update-placefile:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python 3.x
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install requests

      - name: Run placefile generator script
        env:
          YOUTUBE_API_KEY: ${{ secrets.YOUTUBE_API_KEY }}
        run: python generate_placefile.py

      - name: List files in root
        run: ls -la

      - name: Commit and push changes
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add youtube_chasers.txt
          git diff --cached --quiet || (git commit -m "Auto-update placefile" && git push https://x-access-token:${GH_PAT}@github.com/${{ github.repository }} HEAD:${{ github.ref }})
