name: Update YouTube Placefile

on:
  schedule:
    - cron: "*/10 * * * *"
  workflow_dispatch:

jobs:
  update-placefile:
    runs-on: ubuntu-latest

    env:
      YOUTUBE_API_KEY: ${{ secrets.YOUTUBE_API_KEY }}
      GH_PAT: ${{ secrets.GH_PAT }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install requests

      - name: Run script to generate placefile
        run: python generate_placefile.py

      - name: Check if file exists
        run: |
          echo "🧪 Checking for youtube_chasers.txt..."
          ls -l
          if [ ! -f youtube_chasers.txt ]; then
            echo "❌ youtube_chasers.txt not found!"
            exit 1
          fi
          echo "✅ File exists!"

      - name: Configure Git
        run: |
          git config --global user.name "marcosbombi"
          git config --global user.email "marcosbombi@users.noreply.github.com"

      - name: Commit and push if file changed
        run: |
          git remote set-url origin https://x-access-token:${GH_PAT}@github.com/${{ github.repository }}
          git add youtube_chasers.txt
          git status
          git diff --cached --exit-code && echo "🟡 No changes to commit" || git commit -m "Auto-update placefile"
          git push