name: Update YouTube Placefile

on:
  schedule:
    - cron: "*/10 * * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      YOUTUBE_API_KEY: ${{ secrets.YOUTUBE_API_KEY }}
      GH_PAT: ${{ secrets.GH_PAT }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install requests

      - name: Run script
        run: python generate_placefile.py

      - name: Verify file exists
        run: |
          echo "Current directory:"
          pwd
          echo "Listing files:"
          ls -l
          test -f youtube_chasers.txt && echo "✅ File exists" || (echo "❌ File missing" && exit 1)

      - name: Commit and push
        run: |
          git config user.name "marcosbombi"
          git config user.email "marcosbombi@users.noreply.github.com"
          git remote set-url origin https://x-access-token:${GH_PAT}@github.com/${{ github.repository }}
          git add youtube_chasers.txt
          git commit -am "Auto-update placefile" || echo "Nothing to commit"
          git push