name: Update YouTube Chaser Placefile

on:
  schedule:
    - cron: '*/30 * * * *'  # runs every 30 minutes
  workflow_dispatch:        # manual trigger option

jobs:
  update-placefile:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install requests
      run: pip install requests

    - name: Run placefile generation script
      env:
        YOUTUBE_API_KEY: ${{ secrets.YOUTUBE_API_KEY }}
      run: python generate_placefile.py

    - name: Commit and push updated placefile
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git add youtube_chasers.txt
        git diff --quiet || (git commit -m "Auto-update placefile" && git push)
